### ISSUE TITLE
Add attachments

### ISSUE THREAD

**Issue by woheller69** [niendo1/ImapNotes3#6] opened 2023-01-07 10:22 UTC
what do you think about an option to attach documents to a note?

**Comment by niendo1** [comment] 2023-01-07 15:46
in the code itself some body there are already function for this: MakeMessageWithAttachment and GetPart.
But it is not used in the moment.
Also Inline-Images are supported. (but can not inserted at the moment). - this will coma with the v1.1 release.
But again..may time...

**Comment by niendo1** [comment] 2024-11-14 18:55
duplicate of #89

**Closed by niendo1** 2024-11-14 18:55 UTC
Labels: enhancement
